# Récupérer les données BNPE

## La fonction

In [2]:
import requests
from jsonpath_ng import parse # https://github.com/h2non/jsonpath-ng

def récupérer_données_bnpe(url: str, jsonpath_search_pattern: str) -> (list|dict):
    à_retourner = []
    json_brut = requests.get(url).json()
    if json_brut is None:
        return à_retourner
    données_dintérêt = [match.value for match in parse(jsonpath_search_pattern).find(json_brut)]
    if données_dintérêt is None:
        return à_retourner
    return données_dintérêt

## Données « Synthèse géographique »

Département 66, année 2020

In [3]:
annee = 2020
code_dep = 66
url = f'https://bnpe.eaufrance.fr/Bnpe-Diffusion/synthese/synthese_geographique?&code_dep={code_dep}&annee={annee}&ecrasant'
pattern = '$.features[*].properties'
synthese_geographique = récupérer_données_bnpe(url, pattern)

In [12]:
synthese_geographique[:3]

[{'volume': 75002,
  '_SRID': 4326,
  'codeCommune': '001',
  'codeInsee': '66001',
  'codeRegion': '76',
  'codeDepartement': '66',
  'nomCommune': 'Albère',
  'peuple': True},
 {'volume': 300805,
  '_SRID': 4326,
  'codeCommune': '002',
  'codeInsee': '66002',
  'codeRegion': '76',
  'codeDepartement': '66',
  'nomCommune': 'Alénya',
  'peuple': True},
 {'volume': 14170277,
  '_SRID': 4326,
  'codeCommune': '003',
  'codeInsee': '66003',
  'codeRegion': '76',
  'codeDepartement': '66',
  'nomCommune': 'Amélie-les-Bains-Palalda',
  'peuple': True}]

In [15]:
import pandas as pd

df_synthese_geographique = pd.DataFrame(synthese_geographique, columns=sorted(synthese_geographique[0].keys()))
df_synthese_geographique

     _SRID codeCommune  ... peuple      volume
0     4326         001  ...   True     75002.0
1     4326         002  ...   True    300805.0
2     4326         003  ...   True  14170277.0
3     4326         004  ...   True   1424166.0
4     4326         005  ...   True  22210389.0
..     ...         ...  ...    ...         ...
221   4326         230  ...   True  27336179.0
222   4326         231  ...   True         NaN
223   4326         232  ...   True     53126.0
224   4326         233  ...   True         NaN
225   4326         234  ...   True         NaN

[226 rows x 8 columns]